### ISSUE TITLE
Problème sur la météo

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis-weather-wunderground#1]
Bonjour,

D'abord super boulot pour cette super application Jarvis.
J'ai installé la météo, j'ai créé une clé sur le site Weather Underground, et j'ai l'erreur suivante:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'forecast'

Merci pour votre aide

**Comment by alexylem** [comment]
Problème confirmé, chez moi j'ai:
```shell
$> ./jarvis.sh -x "meteo"
$> say "je regarde..." && curl -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json" | python -c "import sys, json; print json.load(sys.stdin)['forecast']['txt_forecast']['forecastday'][0]['fcttext_metric'].encode('utf-8').replace('ºC', 'degrés')" | say
Jarvis: je regarde...
Jarvis: 
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

**Comment by alexylem** [comment]
Problème identifié, je corrige...

**Comment by alexylem** [comment]
Corrigé, mets à jour:
```shell
$>./jarvis.sh -u
```

**Comment by alexylem** [comment]
```shell
$> ./jarvis.sh -x "meteo"
$> say "je regarde..." && say "$(curl -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json" | jq -r '.forecast.txt_forecast.forecastday[0].fcttext_metric' | sed "s/ºC/degrés/g")"
Jarvis: je regarde...
Jarvis: Partiellement nuageux. Minimales : 8 degrés.
```

**Comment by azertigrou** [comment]
Bonjour,

A preésent, j'ai une nouvelle erreur:
parse error: Invalid numeric literal at line 2, column 0

Merci pour votre réponse

2016-10-31 20:21 GMT+01:00 Alexandre Mély <notifications@github.com>:

**Comment by alexylem** [comment]
Tu peux coller le résultat complet de la console en lançant ainsi:
```shell
$> ./jarvis.sh -x "meteo"
```
Et aussi ta config?
```shell
$> cat plugins/jarvis-weather-wunderground/config.sh
```
Merci

**Comment by azertigrou** [comment]
Voici le résultat: 
```
pi@jarvis:~/jarvis $ ./jarvis.sh -x meteo
$> say "je regarde..." && say "$(curl -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json" | jq -r '.forecast.txt_forecast.forecastday[0].fcttext_metric' | sed "s/ºC/degrés/g")"
Jarvis: je regarde...
parse error: Invalid numeric literal at line 1, column 23

```

et pour la config:
```
weather_wunderground_key="maclé" # Get one here https://www.wunderground.com/weather/api/
weather_wunderground_city="France/Paris"
weather_wunderground_language="FR"

```

**Comment by alexylem** [comment]
J'ai remarqué qu'il y avait un problème avec Paris, essaye avec une autre ville juste pour vérifier:
ex: `France/Grasse`

**Comment by azertigrou** [comment]
Ca marche ! Nickel !
En fait, j'habite pas Paris, donc c'est pas grave pour moi !


PS: Merci et vraiment bon boulot pour Jarvis ! A part le fait qu'il faut
que je change de micro car il ne comprend qu'à 1m: j'aurais besoin d'aide
dans le choix d'un micro qui prenne une pièce de 30m², tu peux m'aider?




2016-11-01 12:11 GMT+01:00 Alexandre Mély <notifications@github.com>:

**Comment by alexylem** [comment]
Tu peux trouver des choix de micros ici:
http://domotiquefacile.fr/jarvis/content/prerequisites
L'idéal serait un micro array, discuté ici:
https://github.com/alexylem/jarvis/issues/103
