### ISSUE TITLE
ajouter la météo de demain

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis-weather-wunderground#2]
Désolé, je ne sais pas comment contribuer avec git mais je vais me renseigner pour t'envoyer les modifications/ajouts.

En attendant voici une fonction que j'ai crée qui pourrai être sympa pour la météo du lendemain.

`
jv_pg_ww_tomorrow_weather()
{
curl -o wunderground.json -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json"
WEEKDAY=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1]')
DAY=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1].date.day')
MONTHNAME=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1].date.monthname')
LOWTEMP=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1].low.celsius')
HIGHTEMP=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1].high.celsius')
CONDITIONS=$(cat wunderground.json | sudo jq -r '.forecast.simpleforecast.forecastday[1].conditions')

echo "le $WEEK $DAY $MONTHNAME, il est prévu une température minimale de $LOWTEMP degrés et maximale de $HIGHTEMP degrés.  Les conditions sont : $CONDITIONS"
rm wunderground.json
}

`

Penses-tu qu'il est possible de parser à la volé le json pour renseigner toutes les variables ? Cela éviterai d'écrire dans un fichier puis de l'effacer.

L'autre avantage d'un fichier, c'est que cela économiserai des requetes (qui sont limités) si le fichier a été écrit depuis un certain temps.

**Comment by alexylem** [comment]
Je vais rajouter cette fonctionnalité, effectivement pas besoin de passer par un fichier intermédiaire je crois que weather wunderground propose déjà un texte pré-défini.

**Comment by Gilles76** [comment]
Désolé, je me suis mal exprimé. Je parlai de méthode de traitement de l'information provenant d'une url.

Je fais un cat d'un fichier pour écrire de multiples variables. Est-il possible de renseigner les multiples variables sans passer par un fichier comme je l'ai fait ?

Pour te citer un autre exemple, je vais tenter d'écrire un plugin pour openhab et jarvis. Je vais devoir parser une url au format xml. Selon mes connaissances, Je vais donc être tenté d'écrire dans un fichier temporaire le temps de renseigner mes variables . Tu aurai fais la même chose ou tu as une autre idée ?

Pour en revenir à la météo, en regardant le json de wunderground, il est tout à fait possible de demander la météo sur plusieurs jours. Dans ce que je t'ai passé, il suffirait de changer l'index de forecastday.
On peut imaginer que certaines personnes (dont moi) veulent savoir a un moment donné la météo des prochains jours.

Pas forcément le détails complet mais juste les conditions climatique, a creuser.

**Comment by alexylem** [comment]
Oui je comprends, rien de très sorcier pour le forecast je vais essayer de faire ca.
Pour éviter de passer par un fichier temporaire tu peux aussi stocker le résultat de `curl` dans une variable et le repasser à travers `jq` autant de fois que tu le souhaites.

**Comment by alexylem** [comment]
Implémenté, mets Jarvis à jour:
```yml
Vous: Quelle est la météo pour demain?
Jarvis: je regarde...
Jarvis: Légère pluie. Minimales : 7 degrés. Vents SO soufflant de 10 à 15 km/h. Risque de pluie : 60 %.
```
```

**Comment by alexylem** [comment]
Il y a un problème avec le système de mise à jour:
```shell
Updating jarvis-weather-wunderground-fr...error: Your local changes to the following files would be overwritten by merge:
	config.sh
Please, commit your changes or stash them before you can merge.
Aborting
```

**Comment by Gilles76** [comment]
Normal le config.sh local a été changé par rapport à celui de git.
Comme le config.sh peut êtrre changé, est-ce qu'il ne serait pas judicieux d'avoir un config-default.sh quisera revalidé par git si mise à jour et avoir un répertoire config.d comme on le voit souvent sur linux.
Ainsi toute modification personnel ne sera pas écrasée et l'utilisateur pourra mettre à jour son config.

Si on pousse un peu plus (à froid). l'update devrait indiqué à la personne qui met à jour ce que celle-ci apporte.

**Comment by alexylem** [comment]
1. Avoir un `config.sh` et un `config.default.sh` c'était l'ancienne méthode pour le core de Jarvis. J'ai laissé tombé car à la modif du template de config (ajout nouvelles variables, etc...) il fallait merger les 2 et c'était compliqué pour l'utilisateur lambda. Je suis passé depuis à un système de dossier `config/` avec un fichier par variable. Je me demande si je devrais pas utiliser cette méthode aussi pour les plugins... mais ca complique la mise à jour des variables sans interface utilisateur dédiée...
2. Pour le contenu de la mise à jour (core & plugins), c'est déjà le cas: ca affiche à l'utilisateur la liste des changements (commit messages) avant qu'il accepte ou refuse.

**Comment by alexylem** [comment]
J'ai un autre problème, déjà pas mal de plugins sont publiés, si je change la méthode il faut que je recontacte les auteurs 1 par 1 (sans parler de l'impact sur les utilisateurs)... je vais essayer de trouver une autre solution...

**Comment by alexylem** [comment]
Je pense que pour le moment je vais, uniquement dans le cas ou config.sh a été modifié, écraser la configuration de l'utilisateur, qui sera préalablement backupée dans un config.sh.old afin qu'il puisse reremplir le nouveau...

**Comment by Gilles76** [comment]
Alexy,
Attends avant de faire quoi que ce soit, il n'y a pas grosse urgence. Je n'ai pas encore eu le temps de décortiquer jarvis. Il y a peut-etre d'autres solutions.

**Comment by Gilles76** [comment]
A froid comme ça, pourquoi ne pas avoir un endroit ou stocker tes plugins dans leurs forme brut , comme ça si update tu n'écrases pas la config de l'utilisateur avec git.

Ensuite git n'est plus utilisé et là ça me parait plus simple à gérer, il faudra remanier le fichier de config de l'utilisateur avec les nouvelles variables au préalable commentées qui seront disponible s'il veut l'utiliser.

Je ne suis pas développeur, mais je connais bien linux. Il y a plusieurs possibilités pour mettre à jour un programme. La moins cool, l'utilisateur doit modifier à la main les nouvelles fonctions. Sinon il existe la méthode include qui ne touchera pas un dossier de configuration personnalisée.

Je vois bien que tu vises la simplicité et l'efficacité. Je trouve ça super d'ailleurs. Donc il faut un peut de temps et surtout voir ou tu veux aller pour ne pas t'enfermer vers une solution qui sera difficile à mettre à jour.

**Comment by Gilles76** [comment]
Je n'avais pas vu le stockage des variables dans chaque fichier pour la config. Tu n'as pas peur qu'a la longue le parcours de chaque fichier (qui finira par grossir) ralentisse Jarvis.
Même si c'est pas loin du hors sujet, pourquoi ne pas être resté sur un seul fichier avec des variables données et un numéro de version pour la configuration ?

**Comment by alexylem** [comment]
Pour le fichier de config c'est une méthode assez généralisée dans linux, et pour les plugins de Jarvis ca s'y prête plutôt bien. Je les inclus ainsi dans Jarvis core:
```shell
for f in plugins/*/config.sh; do source $f; done
for f in plugins/*/${language:0:2}/functions.sh; do source $f; done
```
Jarvis évolue très rapidement, généralement je développe les nouvelles fonctions du Core en quelques minutes/heures. Je ne suis pas du genre à "attendre" ni la communauté d'ailleurs 😄 
Je préfère faire les modifs petit à petit et éviter les grosse révolutions pour limiter l'impact sur la communauté et les contributeurs des plugins.
Aucun problème de performance, c'est juste chargé au démarrage une seule fois. Sur un Raspberry Pi c'est instantané (après j'ai pas testé avec 1 million de plugins...).
La solution que tu proposes présente la même problématique, avoir un fichier config "source" à part ne résout pas le problème lors de l'ajout de nouvelles variables. L'utilisateur devra la recopier à la main (surtout que dans certains cas l'absence de cette nouvelle variable sera un problème pour le fonctionnement du plugin...) D'autant plus qu'il ne sera pas forcément au courant.

Je pense que je vais rester sur mon idée initiale mais il faut que je me dépêche car actuellement l'update de tous les plugins sont bloqués à cause de ce problème (d'ailleurs le ticket devrait être dans Jarvis core), et certains d'entre eux on eu des corrections critiques récemment...

**Comment by Gilles76** [comment]
Ok, c'est toi le boss. Je sais que les utilisateurs peuvent être empressés, mais j'ai appris à attendre (pas trop longtemps non plus !)
Effectivement il faut agir pour permettre l'update dans ce cas.

**Comment by alexylem** [comment]
@Gilles76 bon en fait c'est pas aussi évident, `git` ne permet pas de merger avec des changement locaux (à part avoir un compte `git` pour `stash`). Je galère un peu mais dans l'intérêt de l'utilisateur, je pense que je vais essayer manuellement de faire un merge, ou au moins afficher en haut du fichier de config l'ancienne ou la nouvelle version...

Exemple de scénario pour mieux comprendre, et avoir ton avis:

**config.sh server v1**
```shell
city="<YOUR CITY>"
```
**config.sh local v1**
```shell
city="Grasse"
```

Mettons le plugin évolue, il y a une nouvelle variable (et un commentaire est ajouté à une variable existante:

**config.sh server v2**
```shell
city="<YOUR CITY>" # set your city here
metric="<YOUR METRIC>"
```
**Mise à jour**
```shell
$> ./jarvis.sh -u
#config.sh has changed, please update it
```
**OPTION A: config.sh local v2**
```shell
#plugin config has changed, please set it up again
#here below are your old values
#city="Grasse"
city="<YOUR CITY>" # set your city here
metric="<YOUR METRIC>"
```
OR

**OPTION B: config.sh local v2**
```shell
#plugin config has changed, please set it up again
#here below are the new available variables to set (please uncomment)
#city="<YOUR CITY>" # set your city here
#metric="<YOUR METRIC>"
city="Grasse"
```
OR

**OPTION C: config.sh local v2**
```shell
#plugin config has changed, please remove unecessary lines
city="<YOUR CITY>" # set your city here
metric="<YOUR METRIC>"
city="Grasse"
```

L'option C est intéressante car dans la très grande majorité des cas elle fonctionne sans changement (la valeur de la variable de l'utilisateur écrase la valeur de la variable par défaut), mais il faudra tout de même renseigner les nouvelles variables. Par contre elle peut paraître un peu "bizarre" car les variables sont en doubles... (voir triples si plusieurs mises à jour sans nettoyage..)

Tu en penses quoi?

**Comment by Gilles76** [comment]
Merci d'avoir pris le temps de montrer les scénarios.
Personnellement, je préfère le scénario B, car plus conventionnel.
Une des règles d'or c'est de proposer de nouvelles fonctionnalités sans changer l'ancien comportement surtout quand un update n'est pas majeur. Du coup l'utilisateur est averti qu'il y a de nouvelles possibilités et peut les mettre en place quand il le veut.

Le scénario C est bien, pour ma part non conventionnel, et ça peut devenir vite le bazar.

Définitivement le scénario B est bien.

Le 5 novembre 2016 11:11:40 GMT+01:00, "Alexandre Mély" <notifications@github.com> a écrit :
>@Gilles76 bon en fait c'est pas aussi évident, `git` ne permet pas de
>merger avec des changement locaux (à part avoir un compte `git` pour
>`stash`). Je galère un peu mais dans l'intérêt de l'utilisateur, je
>pense que je vais essayer manuellement de faire un merge, ou au moins
>afficher en haut du fichier de config l'ancienne ou la nouvelle
>version...
>
>Exemple de scénario pour mieux comprendre, et avoir ton avis:
>
>**config.sh server v1**
>```shell
>city="<YOUR CITY>"
>```
>**config.sh local v1**
>```shell
>city="Grasse"
>```
>
>Mettons le plugin évolue, il y a une nouvelle variable (et un
>commentaire est ajouté à une variable existante:
>
>**config.sh server v2**
>```shell
>city="<YOUR CITY>" # set your city here
>metric="<YOUR METRIC>"
>```
>**Mise à jour**
>```shell
>$> ./jarvis.sh -u
>#config.sh has changed, please update it
>```
>**OPTION A: config.sh local v2**
>```shell
>#plugin config has changed, please set it up again
>#here below are your old values
>#city="Grasse"
>city="<YOUR CITY>" # set your city here
>metric="<YOUR METRIC>"
>```
>OR
>
>**OPTION B: config.sh local v2**
>```shell
>#plugin config has changed, please set it up again
>#here below are the new available variables to set (please uncomment)
>#city="<YOUR CITY>" # set your city here
>#metric="<YOUR METRIC>"
>city="Grasse"
>```
>OR
>
>**OPTION C: config.sh local v2**
>```shell
>#plugin config has changed, please remove unecessary lines
>city="<YOUR CITY>" # set your city here
>metric="<YOUR METRIC>"
>city="Grasse"
>```
>
>L'option C est intéressante car dans la très grande majorité des cas
>elle fonctionne sans changement (la valeur de la variable de
>l'utilisateur écrase la valeur de la variable par défaut), mais il
>faudra tout de même renseigner les nouvelles variables. Par contre elle
>peut paraître un peu "bizarre" car les variables sont en doubles...
>(voir triples si plusieurs mises à jour sans nettoyage..)
>
>Tu en penses quoi?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/alexylem/jarvis-weather-wunderground/issues/2#issuecomment-258602474

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by alexylem** [comment]
C'est marrant c'est exactement ce que j'ai développé au final 😄 
Je suis en train de le tester avant de committer

**Comment by Gilles76** [comment]
T'es super, merci pour ta réactivité. Me tarde de mettre à jour


Le 5 novembre 2016 13:01:53 GMT+01:00, "Alexandre Mély" <notifications@github.com> a écrit :
>C'est marrant c'est exactement ce que j'ai développé au final 😄 
>Je suis en train de le tester avant de committer
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/alexylem/jarvis-weather-wunderground/issues/2#issuecomment-258607289

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by alexylem** [comment]
Ca y est, tu peux mettre Jarvis à jour, de préférence depuis le menu pour qu'il te fasse revoir les fichier de configuration des plugins à la volée:
![image](https://cloud.githubusercontent.com/assets/11017174/20030071/8a1173ee-a35d-11e6-80c7-f3f0b031e7d6.png)
