### ISSUE TITLE
parse error: Invalid numeric literal at line 2, column 0

### ISSUE THREAD

**Issue by Clovis-krz** [alexylem/jarvis-weather-wunderground#7]
Bonjour, il y a une semaine le plugin fonctionnait très bien pour moi mais depuis ce matin il y a un problème, quand je demande la météo il me dit qu'il regarde et me renvoi la parole. Il m'affiche cette erreur sur la console : 
```shell
parse error: Invalid numeric literal at line 2, column 0
```
Est-ce que cela vous est déjà arrivé ou connaissez-vous la solution de problème ?

**Comment by alexylem** [comment]
```yml
Alex: météo            
Jarvis: je regarde...
Jarvis: Ciel plutôt dégagé. Minimales : 9 degrés.
```
Ca marche chez moi.

Merci de coller le résultat complet de la console après avoir lancé Jarvis en mode Troubleshooting, ou partage une session de ton terminal en utilisant [asciinema](http://asciinema.org):
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
./jarvish.sh -nv # start jarvis directly in troubleshooting mode
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by Clovis-krz** [comment]
Je viens d'essayer aujourd'hui en troubleshootting ça a fonctionné, probablement un bug du serveur météo, car hier quand j'ai essayé de me connecter à weatherground il n'a pas voulu...bref
Merci de m'avoir répondu aussi rapidement, le problème est résolu.
