### ISSUE TITLE
Plugin météo me repond "null" à chaque coups

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis-weather-wunderground#8]
Voici un copier-coller de l'erreur

Denis: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 17 silence 1 0.1 11 1 0.5 11 trim 0 5
DEBUG: speech duration was 10 (10 = 1 sec)
DEBUG: stop_listening hook
DEBUG: curl https://speech.platform.bing.com/recognize/query?version=3.0&requestid=9104719d-20f0-45dc-a8f2-a03db0e5972f&appid=D4D52672-91D7-4C74-8AD8-42B1D98141A5&format=json&locale=fr-FR&device.os=linux&scenarios=ulm&instanceid=E043E4FE-51EF-4B74-8133-B728C4FEA8AA&result.profanitymarkup=0
DEBUG: json={"version":"3.0","header":{"status":"success","scenario":"ulm","name":"donne-moi la météo du jour","lexical":"donne-moi la météo du jour","properties":{"requestid":"18011d98-8730-4e18-bec8-406bb91937c4","HIGHCONF":"1"}},"results":[{"scenario":"ulm","name":"donne-moi la météo du jour","lexical":"donne-moi la météo du jour","confidence":"0.9432056","properties":{"HIGHCONF":"1"}}]}
donne-moi la météo du jour
$> say "je regarde..." && say "$(curl -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json" | jq -r '.forecast.txt_forecast.forecastday[0].fcttext_metric' | sed "s/ºC/degrés/g" | sed -e 's/ N / Nord /' -e 's/ NE / Nord Est /' -e 's/ NNE / Nord Nord Est /' -e 's/ ENE / Est Nord Est /' -e 's/ E / Est /' -e 's/ ESE / Est Sud Est /' -e 's/ SE / Sud Est /' -e 's/ SSE / Sud Sud Est /' -e 's/ S / Sud /' -e 's/ SSO / Sud Sud Ouest /' -e 's/ SO / Sud Ouest /' -e 's/ OSO / Ouest Sud Ouest /' -e 's/ O / Ouest /' -e 's/ ONO / Ouest Nord Ouest /' -e 's/ NO / Nord Ouest /' -e 's/ NNO / Nord Nord Ouest /' -e 's/[kK][mM]\/[hH]/ Kilometre par heure /')"
Roby: je regarde...
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
Roby: null

As tu une idée ?

**Comment by alexylem** [comment]
As-tu renseigné ta clé wunderground ?

**Comment by RobyBioloid** [comment]
Oui, il fonctionné avant. As moins qu'elle ce soit effacée. Je vais vérifier quand même

**Comment by RobyBioloid** [comment]
Après vérification, j'ai bien la clé d'enregistré dans la config
key, city et language sont renseigné

**Comment by alexylem** [comment]
Il se peut qu'il y ait un caractère ou formatage spécial qui fasse planter le parsing.
Le jour ou ca t'arrive (la météo change tous les jours 😄 ), exécute manuellement la commande:
```shell
curl -s "http://api.wunderground.com/api/$weather_wunderground_key/forecast/lang:$weather_wunderground_language/q/$weather_wunderground_city.json"
```
en replaçant les variables et colle le résultat ici, merci.

**Comment by RobyBioloid** [comment]
J'ai teste le plugin aujourd'hui et j'ai la reponse :: null

voici le resultat de la commande
`pi@raspberrypi:~ $ curl -s "http://api.wunderground.com/api/0584bc9dd681b066/forecast/lang:FR/q/France/Drome/Valence.json"

{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  "forecast": 1
  }
		, "results": [
		{
		"name": "Valence",
		"city": "Valence",
		"state": "15",
		"country": "FR",
		"country_iso3166":"FR",
		"country_name":"France",
		"zmw": "00000.445.07549",
		"l": "/q/zmw:00000.445.07549"
		}
		,
		{
		"name": "Valence",
		"city": "Valence",
		"state": "16",
		"country": "FR",
		"country_iso3166":"FR",
		"country_name":"France",
		"zmw": "00000.306.WLFBU",
		"l": "/q/zmw:00000.306.WLFBU"
		}
		,
		{
		"name": "Valence",
		"city": "Valence",
		"state": "26",
		"country": "FR",
		"country_iso3166":"FR",
		"country_name":"France",
		"zmw": "00000.355.07577",
		"l": "/q/zmw:00000.355.07577"
		}
		,
		{
		"name": "Valence",
		"city": "Valence",
		"state": "82",
		"country": "FR",
		"country_iso3166":"FR",
		"country_name":"France",
		"zmw": "00000.328.07524",
		"l": "/q/zmw:00000.328.07524"
		}
		]
	}
}
`

**Comment by alexylem** [comment]
Ok on dirait que Valence n'a pas sa propre station météo. En allant sur le site de weahterwunderground, on voit que la station utilisée est Cheylade:
![image](https://cloud.githubusercontent.com/assets/11017174/25357835/9900498a-293f-11e7-8c95-82a1e8e52dd3.png)
https://www.wunderground.com/q/zmw:00000.445.07549
Essaye donc:
```shell
curl -s "http://api.wunderground.com/api/0584bc9dd681b066/forecast/lang:FR/q/France/Cheylade.json"
```
Pour confirmer tu peux aussi essaye la détection par adresse ip:
```shell
curl -s "http://api.wunderground.com/api/0584bc9dd681b066/geolookup/q/autoip.json"
```
Je l'intégrerai bientôt dans le plugin par défaut pour la détection automatique de la station la plus proche.

**Comment by RobyBioloid** [comment]
Cheylade n'a rien à voir avec Valence. On peut trouver une station plus proche?

**Comment by alexylem** [comment]
Je sais j'ai vu 4h de route de distance ca m'a aussi étonné...
Peux-tu faire cette query:
```shell
curl -s "http://api.wunderground.com/api/0584bc9dd681b066/geolookup/q/autoip.json"
```

**Comment by RobyBioloid** [comment]
Du coup j'ai changé de ville, j'ai pris soyons en ardeche. 

Maintenant ca fonctionne ;)
