### ISSUE TITLE
Dossier 'plugins' est devenue 'plugins_installed'

### ISSUE THREAD

**Issue by RobyBioloid** [alexylem/jarvis-weather-wunderground#9]
Bonjour,

J'ai remarqué que le dossier "plugins" à changé de nom et est devenue "plugins_installed"

Je ne sais pas comment fonctionne les autres avec les plugins mais pour ma part je renseigne souvent le dossier.

Du coup, faut il que modifie le code pour avoir le nouveau chemin ou est il possible de le renommer "plugins" ?

**Comment by RobyBioloid** [comment]
Désolé!

Posté au mauvais endroit

**Comment by alexylem** [comment]
@RobyBioloid pas grave,
Pour des raisons de consistence / logique, je vais le laisser en `plugins_installed/`.
Voici ce que je fais dans mes plugins pour ne pas `hardcoder` le path:
```shell
pg_myplugin_function () {
  local dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "$dir/my_script.sh"
}
```
